### PR TITLE
[PORT] Alacritty

### PR DESCRIPTION
**Pull request by netbrum**
Alacritty's configuration documentation can be found [here](https://alacritty.org/config-alacritty.html).

I wasn't sure where to put the port, so I made a temporary `ports` directory.

alacritty_yorumi

### CODE REVIEW

**Comment by esskayesss** [comment]
hi! sorry for the late response. thanks for the contribution and for linking the config docs for alacritty, thats very handy. i should've documented this earlier but im thinking of adding ports in the following structure: `/get/<apps|libs>/<category>/<app_name>`. 

i have a few suggestions of suggestions for this PR to make it more complete.
- renaming the file as `yorumi-abyss.toml`. this can make it easier for users to simply `import` the colorscheme in their configs [as documented here](https://alacritty.org/config-alacritty.html#general).
- the current theme definition doesn't include definitions for
    - [cursor](https://alacritty.org/config-alacritty.html#s35)
    - [vi_mode_cursor](https://alacritty.org/config-alacritty.html#s36)
    - [search](https://alacritty.org/config-alacritty.html#s37)
    - [hints](https://alacritty.org/config-alacritty.html#s38)
    - [line_indicator](https://alacritty.org/config-alacritty.html#s39)
    - [footer_bar](https://alacritty.org/config-alacritty.html#s40)
    - [selection](https://alacritty.org/config-alacritty.html#s41)
- a small `README.md` with basic instructions would help. 

in case you're busy, lmk and i can commandeer your contribution further. i'm grateful for the interest.

**Comment by esskayesss** [comment]
Added ports for alacritty. You can check them out [here](https://github.com/yorumicolors/yorumi/tree/main/get/apps/terms/alacritty). Please report issues if you come across any.

Thank you for the contribution and the interest <3 

---

Screenshot 2024-10-02 at 1 31 53 PM
Screenshot 2024-10-02 at 1 32 16 PM

**Comment by netbrum** [comment]
Hey, nice work adding the last details.

Next time, you might want to commit to the branch in the pr (`alacritty-port` in this case) and merge the pr afterwards. By closing it instead of merging, you essentially "refuse" my contribution (the config for alacritty I made).

You also seem to be using a lot of colors for the alacritty theme that aren't in the [palette](https://github.com/yorumicolors#palette).

**Comment by esskayesss** [comment]
im sorry i was in the process of tweaking the palette slightly and since it was unpublished, it would've been a lot of work that you don't owe me. (this is something akin to an imposter syndrome lol)

> you essentially "refuse" my contribution

that wasn't the intention. i was temporarily using a different device and over there, i had committed changes to main already. but i can see how it can make the work feel discredited. i should've kept that in mind. my apologies for that. your pr is greatly appreciated.

> seem to be using a lot of colors for the alacritty theme that aren't in the [palette](https://github.com/yorumicolors#palette).

i've made a dev branch for yorumi.nvim. more colors had to be added to accommodate the light theme highlights. i ended up being stricter with the color values and tweaking them around a bit. this is where i'm at right now. i will update the docs once i'm happy with the new palette. the theme is pretty new so its only natural for things to change. i will make another post once its stable and ready to be ported without further changes.

image

**Comment by netbrum** [comment]
No worries, I just wanted to let you know in case other people start contributing.

The theme is great so far, I'm a big fan.

**Comment by esskayesss** [comment]
@netbrum i [noticed](https://github.com/alacritty/alacritty-theme/) that a lot of alacritty themes have their own repos. would you be interested in maintaining a yorumi alacritty theme repo?

**Comment by netbrum** [comment]
> @netbrum i [noticed](https://github.com/alacritty/alacritty-theme/) that a lot of alacritty themes have their own repos. would you be interested in maintaining a yorumi alacritty theme repo?

I'm afraid I'll have to decline. I'd love to contribute whenever I can, but I don't feel like maintaining a repository.

**Pull request closed without merging**
